apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-webhook
webhooks:
  - admissionReviewVersions:
      - "v1"
      - "v1beta1"
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVDakNDQXZLZ0F3SUJBZ0lVTDExSFFpMHVHVVVlTkhHRWUrenZVZndKUTlVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dad3hDekFKQmdOVkJBWVRBbFZUTVJNd0VRWURWUVFJRXdwRFlXeHBabTl5Ym1saE1SWXdGQVlEVlFRSApFdzFUWVc0Z1JuSmhibU5wYzJOdk1Sb3dHQVlEVlFRS0V4RlZjMlZrSUVObGNuUnBabWxqWVhSbGN6RXBNQ2NHCkExVUVDeE1nU0dGemRHbHNlUzFIWlc1bGNtRjBaV1FnVm1Gc2RXVnpJRVJwZG1semIyNHhHVEFYQmdOVkJBTVQKRUVGMWRHOW5aVzVsY21GMFpXUWdRMEV3SGhjTk1qRXhNakV5TURBd05UQXdXaGNOTWpZeE1qRXhNREF3TlRBdwpXakNCbkRFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ1RDa05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNUCkRWTmhiaUJHY21GdVkybHpZMjh4R2pBWUJnTlZCQW9URVZWelpXUWdRMlZ5ZEdsbWFXTmhkR1Z6TVNrd0p3WUQKVlFRTEV5QklZWE4wYVd4NUxVZGxibVZ5WVhSbFpDQldZV3gxWlhNZ1JHbDJhWE52YmpFWk1CY0dBMVVFQXhNUQpRWFYwYjJkbGJtVnlZWFJsWkNCRFFUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFKV2xMY3pZUEdTRlc4aElFRnE3M3p6dlFtR1hEOUhsUkwvT3ZJUWI0YmcvYWZoem55TW05WXBFSmE0R1hIM2kKeGRaanVnWFhhVW40ekV2TFZwenlBSXRSTWNWQ1F6WDRCU3RsQ2ExQnJCODhMQkZXYkhEUTZVeEZxMG9KZDV5dAp0enk5aVQ1RlRJUHY5dkM2UXRnSW5KQnIvdHZlRmY0Tm02MmY3dzNDdHd1OTBtWXQraC9zMmJEM2U3azA2U2h0CmVFWGpXdExuajhEL0xDOVhsNm5OTjh5SWNyWm0xQ2x4RFVrSm5OcWlxZEhoTHkrejVVOE9ubkFPTGJmdjhKblkKejJwU3BBWThBUncyclAxbDRjcFYydlJUOGdyOTB3eFVjeXdVQnVMa3FQa3ZySnZNdjVXSFpwR0JHMHFkbGFxQQp0OWlKaXhYSFlPR0xSMzhKYmlOVzlMRUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGS3NvSG9jNTVxbC9sY0N0dlJxaHRjTjd6STlVTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQnpMYUhQa0ZiZys5cW1MT3lyZ2dnT3RiQWRsMVNvWDE0Wmp4ZXVzRVc1U2lydwpXUnVaKzhJcFRsYjdiZ1pOOWw4YkdtZXBPSjFZWGpiRFhMWm9iUG0vZ2QzR0ZuUGlPUFdRSDR5WUJzaGJXT1JCClMybUNDL0Q5Z3M2MlRkZVE2YjN4UXh2SlpEY1U1TkRyeFpRVzFSalFsYSs0MlEwODhDWXM2blRUSkV4QkswMUoKOGh0Z3QrYWMwY3h5dzBDeXJUVi90V2JEUTNvNm1nQlpXREF5aUZ3QlhJa2dyR2pYT0pGN25abmhUUUcxQkhVawp6c2RuenBkLzU3Vk1qNGtjaWRXM243N0I4eW9GT2FqWng4TmVFVUVNcSsxWCtseG8zRS91SU1aWUpkSDd4c0kwCmdSMnZaODdEUnN3SGRDSWFRakZmejkyNXRaOFhrQy9tWXA5ZEdQUWQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      service:
        name: example-webhook
        namespace: default
        path: "/mutate"
    name: example-webhook.default.svc
    sideEffects: None
    objectSelector:
      matchLabels:
        example-webhook-enabled: "true"
    rules:
      - apiGroups: [""]
      - apiVersions: ["v1"]
      - resources: ["pods"]
      - operations: ["CREATE"]