apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-webhook
webhooks:
  - admissionReviewVersions:
      - "v1beta1"
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVDakNDQXZLZ0F3SUJBZ0lVZFZtdjVKOUdyTTMvNmRDeTJnUnlkVUFxM2hzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dad3hDekFKQmdOVkJBWVRBbFZUTVJNd0VRWURWUVFJRXdwRFlXeHBabTl5Ym1saE1SWXdGQVlEVlFRSApFdzFUWVc0Z1JuSmhibU5wYzJOdk1Sb3dHQVlEVlFRS0V4RlZjMlZrSUVObGNuUnBabWxqWVhSbGN6RXBNQ2NHCkExVUVDeE1nU0dGemRHbHNlUzFIWlc1bGNtRjBaV1FnVm1Gc2RXVnpJRVJwZG1semIyNHhHVEFYQmdOVkJBTVQKRUVGMWRHOW5aVzVsY21GMFpXUWdRMEV3SGhjTk1qRXhNakV5TURneU1EQXdXaGNOTWpZeE1qRXhNRGd5TURBdwpXakNCbkRFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ1RDa05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNUCkRWTmhiaUJHY21GdVkybHpZMjh4R2pBWUJnTlZCQW9URVZWelpXUWdRMlZ5ZEdsbWFXTmhkR1Z6TVNrd0p3WUQKVlFRTEV5QklZWE4wYVd4NUxVZGxibVZ5WVhSbFpDQldZV3gxWlhNZ1JHbDJhWE52YmpFWk1CY0dBMVVFQXhNUQpRWFYwYjJkbGJtVnlZWFJsWkNCRFFUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFPbGowL2tad2N5YTErQ1BPTDhHSklPUXREVS8vVElEWFJkZzk0R2ZvMUtIVkYzT1UwdVk0UHRjNnZJaDNGUVAKdVlOclhtT2IvaDlZN1NWRUoyQW1QemJBYjNVSTNaaFRTSUJXRmZqOXlCYWxNTytZMWpLT0dINW10WHQ5U1dMcQorUStvbEVhNVdnVzAvTTJ2SDYrajVWSWFYNTdycm80ei9xMTllazRnay9hcWM2cVpBR3AyUUFQNDVqS2ttemNQCjd4U3lMdDN4TGZybHcwbW96aXlWOVBqM2lhVXpqYWowQ2tudFJ3RUZsaVpFZXE1ME1LVzhESzlGejJxUU9jTlUKUHB2Z3ZRMlRlby9uQVQwVHgrZzRuclNUU1ovcStVNDIydnAzQmY0eExoKzZOT0l2SDlFUXNrYlBNTzArZHFJdgpQZklkREhiNGRucXEyaGtvUzlTQzg4MENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGQWNpNVg4aEdraHdTYmxvOVlYamxFZWJXWGlyTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRRGJqN2tMMWVqaGVDOCtNWkJQRTlPWnR0UUJ2VE9tUm9zUUVCTmdEN3gwVmd2OQpNZVpxVENCU1JpUnJVeHpDSC9YUStoRU1mQ2RwajNRK0pOVW1uMGlPSVpXTG9IVWl1R2xKTHQ0MUJwcHgweVhLClNIVUpOTk44VGlldkJhRFNtUENuSmNiL3pnclFacWpyUjJQanNkeWlLSG1ISXpGN3prazYybnAzOWFMMjRHdm4KdUhabTd2MW5vcXZtMUxzQnlJcHJvNTNpVElPYWRoamwzZXlBOEo4ZnM3M2dVckFyVnZ5dWxaWk1RRnFiOXliSApSU0ZxUGw1azJOcTBTUnErTE1xL1NBdGx3K09tVGFJMEY5NW1YR1FDM0RGRXhQbW53aXpKUzNxRWxOTjJsZFpHCjVJZWdnd2ZiYVFTdXgzQmdIenc0eDNLdXhLSitEVllueVRLMWJqL3oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      service:
        name: example-webhook
        namespace: default
        path: "/mutate"
    name: example-webhook.default.svc
    sideEffects: None
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        example-webhook-enabled: "true"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
